In [4]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [5]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [6]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [7]:
df.dropna(inplace=True)

In [8]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [26]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [27]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [ ]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))
#cross validation score is a function that takes a model, the data, the target, the scoring method and the number of folds for cross validation. It returns an array of scores for each fold. We take the mean of these scores to get an overall accuracy of the model.
# this is a very basic model and we can improve it by adding more features, doing feature engineering, or using a different model.

np.float64(0.6933333333333332)

## Applying Feature Construction

In [28]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1 
# we can create a new feature called family size by adding the number of siblings/spouses and the number of parents/children and adding 1 for the person themselves. This feature might be useful because it can capture the effect of having a family on survival. For example, people with a larger family size might have a higher chance of survival because they can help each other, or they might have a lower chance of survival because they have to share resources. We can test this by adding this feature to our model and seeing if it improves the accuracy.

In [29]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [30]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [22]:
myfunc(4)

1

In [31]:
X['Family_type'] = X['Family_size'].apply(myfunc)
#apply is a function that applies a function to each element of a series. In this case, we are applying the myfunc function to each element of the Family_size column. This will create a new column called Family_type that will have the values 0, 1, or 2 depending on the family size. We can then use this new feature in our model and see if it improves the accuracy.

In [34]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [35]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)
# X[usecols=['Age','Pclass','Family_type']].head()

KeyError: "['SibSp', 'Parch', 'Family_size'] not found in axis"

In [36]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [37]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)

## Feature Splitting

In [38]:
df = pd.read_csv('train.csv')

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [42]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]
#expand is a parameter that tells the split function to return a dataframe instead of a series. This way we can access the different parts of the name easily.

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: str

In [44]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]
# split function is a string method that splits a string into a list of substrings based on a delimiter. In this case, we are splitting the Name column first by ', ' to separate the last name from the title and first name, and then we are splitting the second part by '.' to separate the title from the first name. This will create a new column called Title that will have the titles of the passengers, such as Mr, Mrs, Miss, etc. We can then use this new feature in our model and see if it improves the accuracy.

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: str

In [45]:
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [ ]:
(df.groupby('Title').mean()['Survived']).sort_values(ascending=False)
#"Group passengers by title (Mr, Mrs, Miss), compute average values, then show average survival rate for each title."
#groupby is a function that groups the data by a certain column and then we can apply an aggregation function to get the mean survival rate for each title. This can help us understand which titles had a higher chance of survival and which had a lower chance. For example, we might find that people with the title 'Mrs' had a higher survival rate than those with the title 'Mr', which could be due to various social factors at the time of the Titanic disaster.

Title
the Countess    1.000000
Mlle            1.000000
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Rev             0.000000
Jonkheer        0.000000
Don             0.000000
Capt            0.000000
Name: Survived, dtype: float64

In [ ]:
# from xxlimited import new


df['Is_Married'] = 0
# # Create a new column.
# # Fill every row with 0.
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1#This updates rows where Title is Mrs.
# .loc[condition] ->.loc selects rows satisfying condition.
# .loc[df['Title']=='Mrs']
# selects:
# Name	Title
# Mary	Mrs
# Sarah	Mrs
# Assign 1.
# "Create a new column called Is_Married. Start with 0 for everyone, then set 1 for passengers whose Title is Mrs."


# 1. loc → Label-based indexing
# loc uses row names (labels) and column names.
# |   | Name | Age |
# | - | ---- | --- |
# | a | John | 25  |
# | b | Mary | 30  |
# | c | Tom  | 35  |
# df.loc['b']
# | Name | Age |
# | ---- | --- |
# | Mary | 30  |
# Example 2 — Select specific row + column
# df.loc["b", "Age"]
# output = 30
# ex->condition
# df.loc[df['Age'] > 30, 'Name']




# 2. iloc → Integer Position-based indexing
# df.iloc[row_position, column_position]
# iloc uses numeric positions.
# | Position | Name | Age |
# | -------- | ---- | --- |
# | 0        | John | 25  |
# | 1        | Mary | 30  |
# | 2        | Tom  | 35  |
# df.iloc[1, 0]
# output = 'Mary'

C:\Users\Asus\AppData\Local\Temp\ipykernel_8912\1591796396.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1#This updates rows where Title is Mrs.

In [49]:
df['Is_Married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64